typography_spectrum: 0.883591775316745
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8599067588802427
  lightness: 0.0857491921633482
  saturation: 0.9509915185626596
  rhythmicContrast: 0.4416919881477952
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.025383824482560158
analytics:
  google: null
  facebook: null
  twitter: null
name: GCheyss
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Check '
purpose: []
